import type { Metadata } from "next";
import { Alegreya, Alegreya_Sans } from "next/font/google";
import "./globals.css";

const alegreya = Alegreya({
  variable: "--font-alegreya",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  style: ["normal", "italic"],
});

const alegreya_Sans = Alegreya_Sans({
  variable: "--font-alegreya_Sans",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Alegreya:wght@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${alegreya.variable} ${alegreya_Sans.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
